### ISSUE TITLE
dynamic updates are now broken

### ISSUE THREAD

**Issue by ktsaou** [bernii/gauge.js#100]
Hi,

thank you for this excellent gauge library. I use it in [netdata](http://my-netdata.io/).

Commit c27b989c290a06f506b563c2bcdbdf9c2e79c1c0 breaks dynamic updates. After this commit, updating the value of the chart during runtime, animates it from the minimum value on every update, like this:

![test1](https://cloud.githubusercontent.com/assets/2662304/19020658/f0637572-88b7-11e6-9312-efb2f7cc02e8.gif)

It should be animating from the previous value to the new. To see the difference, just go to a [netdata dashboard](http://london.my-netdata.io/default.html)

For this reason, I use commit d5260c3 in netdata.

**Comment by VMF214** [comment]
samething for me

**Comment by kplindegaard** [comment]
Should be working again now (364a42b7efaad94bc36de9196155e12c69886074). Please check it out.
Unfortunately, it appears that I messed up the pointer length scaling while ensuring support for gauge larger than 180 degrees angle. Thus, you may want to adjust your pointer length if you pull the recent updates.

**Comment by ktsaou** [comment]
v1.3.1 works! thanks!

(ps, I have a new issue with 1.3.1 - I'll open a new issue right away).
