### ISSUE TITLE
Get gauge object by ID/class

### ISSUE THREAD

**Issue by virbose** [bernii/gauge.js#104]
Is there any way to get the Gauge object for updating by its ID or class name? 

I am trying to set up a page with multiple gauges which are updated via AJAX every few seconds. The gauges are dynamically generated based on the number of objects so I would like to be able to retrieve them via something other than their variable name as that will only reference the last item. 

I am not sure if this is beyond the scope of this project.

**Comment by kplindegaard** [comment]
Maintaining a list of all the gauge objects you make should be easy for you, so what do you really mean? Do you mean that you don't know how many canvas-tags you will be needing on your page? You need those to start with anyway. Do you intend to decide at run-time how many canvases you are going to display/create and create gauges inside them again? If that's your thing, I would suggest you try angular and set up a directive for gauge.js, see e.g. [this repository](https://github.com/schlunsen/angular-gaugejs) for an example. That way it is pretty easy to accomplish this.

**Comment by virbose** [comment]
> Do you intend to decide at run-time how many canvases you are going to display/create and create gauges inside them again?

That's what I want to do, so I will look into the mentioned repository, thanks!

**Comment by kplindegaard** [comment]
@virbose, I hope you are well on your way. I am closing this issue now, because your wish is out of scope for gauge.js and should be dealt with using other means.
