### ISSUE TITLE
Update when user votes

### ISSUE THREAD

**Issue by greylien** [bernii/gauge.js#11]
Hi the gauge is brilliant. 

I am trying to use this gauge to update dynamically when a number I have in the database changes. 
The number I have in the database is the vote count. I want it so when the user adds a vote which is recorded, the gauge animates.

Can you give me an idea of how to go about this?

thanks!

**Comment by bernii** [comment]
Sure, you can easily update gauge value via gauge.set(newValue) method. Check out this jsfiddle: http://jsfiddle.net/aYqPT/1/

To get data from DB you can make ajax calls periodically or use some push/comet server. If you want me to elaborate on sth just let me know ;)

**Comment by greylien** [comment]
thanks for your quick response!

The jsfiddle was useful, I will have to use ajax calls which I haven't really used much yet. What is push/comet server? The gauge plays a pretty major role in my site, so will show you it when I've got it all finished.

**Comment by greylien** [comment]
How would I go about changing the overall size of the gauge? 

--solved this now, i see it simply the canvas width and height !

**Comment by bernii** [comment]
Glad you have that solved, closing!
