### ISSUE TITLE
gauge labels get cutoff

### ISSUE THREAD

**Issue by nailbuster** [bernii/gauge.js#111]
really like this gauge..thanks...

my gauge labels seem to get cutoff within the canvas when i'm using - (negative) angle:  

Don't know if there's a simple way to add a 'margin' or something around gauge so it can fit....

notice that the labels seem to get cutoff:

![gaugetest](https://cloud.githubusercontent.com/assets/17054874/22176872/282be82e-dfe1-11e6-9345-444ecee16a51.png)

**Comment by kplindegaard** [comment]
Well, I introduced this bug. Sorry... Didn't notice it (see below where my labels are always in the corners of the canvas rectangle) until after the implementation, and now haven't had time to do anything about it.
One option is to introduce a scaling factor for the gauge radius, but I haven't thought much about it. I will try to find some time to fix this. I may have to introduce a new config parameter, though.

BTW: Did you notice the other bug that came with the static labels?

![image](https://cloud.githubusercontent.com/assets/5760583/22569146/b1697782-e996-11e6-8d25-1168a8315f57.png)

**Comment by jpost** [comment]
I am seeing this issue reoccur for a slightly different gauge configuration. You can see I've set labels corresponding to the min and max at -6250 and 6250, and both labels are getting clipped.

![image](https://cloud.githubusercontent.com/assets/723588/24058798/87308582-0b1a-11e7-9e08-99391d5d9f63.png)

**Comment by kplindegaard** [comment]
Yup. The labels exceed the height of the canvas in your case. You have three choices (at least): Reduce the label font size, make a new label style that allows you to also set label text alignment (e.g. left, right, center), or tweak the trigonometry the gauge can be translated up/down and to the side from the canvas center.

**Comment by jpost** [comment]
Thanks, I will try some of those ideas.

**Comment by jpost** [comment]
After some experimentation, I found that using 0.3 as the value for Gauge.prototype.paddingBottom (instead of the default of 0.1), the canvas was large enough at the bottom to accommodate significantly longer labels at the min and max of my gauge.
