### ISSUE TITLE
v1.3.1 min value shows broken chart

### ISSUE THREAD

**Issue by ktsaou** [bernii/gauge.js#116]
If the value requested is the minimum value, this is what happens:

![image](https://cloud.githubusercontent.com/assets/2662304/22623476/dac33a08-eb64-11e6-901d-c0f336ee5a49.png)

As a work around I just added 0.001 to the minimum value to have the chart rendered properly.

**Comment by kplindegaard** [comment]
The problem with minValue and first rendering, i.e. gauge.set( minValue ) has been there quite a while. 
@johanye's new option 'limitMin comes to the rescue, so you may want to try enable that.

`var opt = {`
`  // your other options`
`  limitMin: true`
`};`

`gauge.setOptions(opt); gauge.set(0);`


I think that should sufficient in your case as an alternative workaround. But you do have a point, there is something fishy there.

**Comment by ktsaou** [comment]
@kplindegaard thanks!

I already have `limitMin: true`. This issue appears with that in place: https://github.com/firehol/netdata/pull/1725/files

**Comment by kplindegaard** [comment]
@ktsaou You are right! What a bummer... I am forcing an update when you do the first .set() operation now in the latest commit. I hope that should pull it off. Do mind testing again with the latest commit, please?

**Comment by ktsaou** [comment]
tested 1.3.2 - it works nicely.

**Comment by ktsaou** [comment]
thank you!
