### ISSUE TITLE
iPhone and iOS

### ISSUE THREAD

**Issue by andyscott12** [bernii/gauge.js#12]
Hi there,

Just wondering whether this works on the iphone or the iOS ?

Would be awesome if you were able to change the colors based on the value selected - so it means you could have 

0-25% - red
25%-50% - green
50%-75% - purple 
etc

?

**Comment by bernii** [comment]
1. Tested on iPhone simulators iOS 4.3: WORKS (some problems with automatic creator though), iOS 5: WORKS, iOS 6: WORKS
2. Added option of defining custom color renderer! Check out sample code that implements your idea: http://jsfiddle.net/berni/KM7PW/
