### ISSUE TITLE
Generate Multiple Gauge Chart on single page. 

### ISSUE THREAD

**Issue by shuheen** [bernii/gauge.js#121]
Hi,

I have a table with some content and i want to generate gauge in a column of table in each row. and there will be one button along with each gauge to update corresponding gauge value.

Suppose if i click Second row button so it should update value of second row gauge only..

Below is the screen shot what i want.

![capture](https://cloud.githubusercontent.com/assets/7921016/22854635/f9bf179a-f098-11e6-9ed7-5ae77b0ce879.PNG)

please help

**Comment by kplindegaard** [comment]
Can you please be a bit more specific?
It's entirely up to you to create as many as you want.

**Comment by shuheen** [comment]
Thanks.. @kplindegaard for the quick response.

I have updated the description. As i am creating table dynamically in loop... so gauge will also be generate with loop.. Table row could be 10,1000,10000 and so on according to requirement.

**Comment by kplindegaard** [comment]
If you want to make this generic and have an arbitrary number of rows, I think you should consider angularjs. There might be other tools you are familiar with, but I have used angular a few times to achieve this with good results. There is a link in issue #104 to an angular directive that should get you going. 
Good luck :)

**Comment by kplindegaard** [comment]
Closing this issue for now. It has been answered. See comments above.
