### ISSUE TITLE
Tick lines in gauge 

### ISSUE THREAD

**Issue by rajeshv-optimus** [bernii/gauge.js#129]
Hello @bernii 

**I have created like** 
![gauge-chart2](https://cloud.githubusercontent.com/assets/10668663/24240155/9f1de1b0-0fd6-11e7-9e0f-e0421253a039.png) 

**but i want it like** 

![gauge-chart1](https://cloud.githubusercontent.com/assets/10668663/24240173/b18058f6-0fd6-11e7-8cb6-b6b44be1da36.png)

![gauge-chart3 png](https://cloud.githubusercontent.com/assets/10668663/24240312/16d56c32-0fd7-11e7-840a-66cb4f1211f9.png)

**Please guide if we can do this for the same**

**Comment by kplindegaard** [comment]
Sure thing. You can absolutely try do this. Please make a fork of the repos, make the necessary changes, submit a pull request that we can have a look at.

**Comment by Knight2601** [comment]
Check out v1.3.6 (when it's released), where we have implemented major/minor ticks which are customizable.
