### ISSUE TITLE
I want to make this Gauge work in IE 8 and Below.

### ISSUE THREAD

**Issue by theredbaron** [bernii/gauge.js#13]
Any Help Regarding the issue will be appreciated.
I want to use the following Gauge Meter in all the browsers, but for some reasons I need to implement the meter in IE8 and Below.

**Comment by sergiocampama** [comment]
+1, yes please

**Comment by bernii** [comment]
As IE8 does not have canvas support you have to use some polyfill. I added excanvas IE canvas polyfill (http://code.google.com/p/explorercanvas/) to the project page (http://bernii.github.com/gauge.js now works with IE8). 

To use it you have to add excanvas to head of your webpage as on gauge.js homepage:



After that gauge.js should be workin pretty smooth ;-) Made some changes so it works with excanvas polyfill.
