### ISSUE TITLE
White Outline on Donuts

### ISSUE THREAD

**Issue by atajsic** [bernii/gauge.js#14]
On the background arc on the donut, there is a white border that is apparent.

Example: http://i.minus.com/i8TxS4zFkaPRN.png

by multiplying @lineWidth by 0.8 on the following line, the issue is fixed.

https://github.com/bernii/gauge.js/blob/gh-pages/dist/gauge.coffee#L358

``` coffee
@ctx.lineWidth = @lineWidth * 0.8
```

Fixed Example: http://i1.minus.com/iZdEDhXnpvuTM.png

EDIT: As you may have noticed- I changed the ends to be butt- perhaps add an option to choose either round or butt for the donut?

**Comment by jacksoncapper** [comment]
You're awesome!
