### ISSUE TITLE
Gauge positioning within canvas

### ISSUE THREAD

**Issue by kerrinhardy** [bernii/gauge.js#142]
I have four gauges in a row on a dashboard.  The gauges seem to have a left margin / padding that is not able to be changed.  For a couple of gauges this leads to the arrows overlapping.  

![2017-07-11 13_30_49-gauge](https://user-images.githubusercontent.com/4270798/28050580-af2cd594-663d-11e7-8baf-06e166de9ad3.png)
The canvas 'border' is highlighted in screenshot.
Adding the following does not seem to affect the placement of the gauge within the canvas:
```
gauge.paddingLeft = 0;
gauge.marginLeft = 0;
```
Does anyone have any ideas to either left align or center the gauges within the canvas?

**Comment by kplindegaard** [comment]
The gauge will render horizontally centered within the canvas. For example, here I have two div's side by side where each one contains a canvas with non-standard background color filling the entire div.
![image](https://user-images.githubusercontent.com/5760583/28209207-da2aa7de-6891-11e7-98a2-41d9d2ef8ee4.png)
This example looks OK to me....

Are you sure you have aligned and set the sizes of your canvases correctly in the html section of your page?

**Comment by kerrinhardy** [comment]
Yes, it was a problem with Bootstrap columns.  Once that was fixed, the gauges line up perfectly.
Sorry for not getting back here sooner.
