### ISSUE TITLE
Help for a noob :)

### ISSUE THREAD

**Issue by thecatz** [bernii/gauge.js#15]
Hello i've trouble to display the gauge can someone tel me what are going wrong on my code please? ( have replace here "< " with "( " to display the code)

thx

<pre>
(html)
(head)
<script src="http://bernii.github.com/gauge.js/dist/gauge.js" type="text/javascript" language="javascript" script>

<script>
var opts = {
  lines: 12, // The number of lines to draw
  angle: 0.15, // The length of each line
  lineWidth: 0.44, // The line thickness
  pointer: {
    length: 0.9, // The radius of the inner circle
    strokeWidth: 0.035, // The rotation offset
    color: '#000000' // Fill color
  },
  colorStart: '#6FADCF',   // Colors
  colorStop: '#8FC0DA',    // just experiment with them
  strokeColor: '#E0E0E0',   // to see which ones work best for you
  generateGradient: true
};
var target = document.getElementById('foo'); // your canvas element
var gauge = new Gauge(target).setOptions(opts); // create sexy gauge!
gauge.maxValue = 3000; // set max gauge value
gauge.animationSpeed = 32; // set animation speed (32 is default value)
gauge.set(1250); // set actual value
</script>

(head)
(body)
(canvas id="foo") (/canvas)

(/body)
(/html)

</pre>

**Comment by bernii** [comment]
Hi @thecatz !
There are couple things that could be improved to make it work:
1. Maybe that's just a misspelling but you have no closing tag for head ( you've got two (head), where one should be (/head)
2. No end tag for (script)
3. No gauge JS lib include! - You would get 'Uncaught ReferenceError: Gauge is not defined' in your web browser console if the rest was right.
4. If you want to place your JS inside the (head) content you need to load it after gauge.js and canvas (which is in the body) is loaded. To do this you can use window.onload event (check out the html file linked below and http://stackoverflow.com/a/807895)

Fully working JS fiddle with your code: http://jsfiddle.net/berni/yzy8G/
Sample HTML page with your code: http://extensa.pl/projekty/gh/gauge_issue1.html

**Comment by thecatz** [comment]
thx for your help
