### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by lewsid** [bernii/gauge.js#159]
I noticed a couple typos in the documentation, and, though you say to contact you via email with issues or questions, I'm unable to find your email address anywhere so I just thought I would kick it over via an issue.

1. Under "Advanced Options: Percentage Color," you've mispelled the word "behaves."
2. Under "Advanced Options: Tick marks," your code sample is missing quotes around the color values. Perhaps that's just the CoffeeScript syntax, but it fails in vanilla JS, and the sample doesn't specify one way or the other.

Anyway, thanks for this excellent tool, please keep up the good work!

**Comment by Knight2601** [comment]
fixed, thanks for pointing it out :)
