### ISSUE TITLE
latest version for cdnjs

### ISSUE THREAD

**Issue by ggerber** [bernii/gauge.js#177]
Hi,

Can you tag the latest 1.3.6 version, so that cdnjs can host it?
Cdnjs is hosting the 1.3.5 version and will only update to 1.3.6 if it is tagged at 1.3.6.

See issue below:
https://github.com/cdnjs/cdnjs/issues/12614#issuecomment-377844911

**Comment by kplindegaard** [comment]
Version 1.3.6 is now tagged and released now.
As suggested in #167 , I have also done `npm publish` so it's possible to fetch the latest and greatest with `npm install gaugeJS`.
