### ISSUE TITLE
Numbers on the gauge scale are written off the canvas

### ISSUE THREAD

**Issue by ktecho** [bernii/gauge.js#178]
Hi,

I don't know if a little more margin is needed or if I'm doing something wrong, but can't get this to print the whole "50" number inside the canvas:

[https://www.ktecho.com/heart3/index.html](https://www.ktecho.com/heart3/index.html)

In some browsers like Firefox it's even worse. In Chrome/Chromium there is only a little bit of the number off-canvas, but in Firefox half the number is missing.

**Comment by kplindegaard** [comment]
Have your tried to reduce the radiusScale parameter just a little bit? That decrease the gauge radius, and the labels should follow.

**Comment by ktecho** [comment]
@kplindegaard  Thanks a lot, I confused that parameter with another one. Anyways, maybe this should be fixed so even if you specify 100%, it fits in the canvas.

But for me it's enought. Thanks!
