### ISSUE TITLE
Please help me. what is the process to add current value?? I am new, please help me.

### ISSUE THREAD

**Issue by opu8232** [bernii/gauge.js#186]
Please help me. what is the process to add current value?? I am new, please help me. 
                                                                                        

![capture](https://user-images.githubusercontent.com/20215069/43004257-f932b6b0-8c50-11e8-8eeb-b5b057c34530.JPG)

**Comment by kplindegaard** [comment]
You have probably figured it out by now, e.g. if you searched old issues like #19. Anyway, here we go:

  1. Define a `div`, `span` or whatever you like and give that html element a decent id.
  1. After creating the Gauge or Donut, get a reference to that element and pass it to the Gauge object via the `setTextField` method.

```
<body>
  <canvas id="my_canvas"></canvas>
  <span id="my_textfield"></span>

<script type="application/javascript">
var opts = {
   // Deleted the contents of this. Use your own config.
};
var target = document.getElementById('my_canvas'); 
var gauge = new Gauge(target).setOptions(opts); 
gauge.maxValue = 8000; 
gauge.setMinValue(0); 
gauge.animationSpeed = 32; 

// Assign text field
var textField = document.getElementById("my_textfield");
gauge.setTextField(textField);

gauge.set(5000);
</script>
</body>
```
