### ISSUE TITLE
Instructions for displaying value alongside gauge?

### ISSUE THREAD

**Issue by sodevious** [bernii/gauge.js#19]
I'd like to display the value of the gauge alongside the canvas, as in your preview. Are there instructions for this?

**Comment by BFTrick** [comment]
I didn't find any instructions but looking through the source code you can create an empty element and then when you're creating the gauge you just have to tell the gauge.js script which element to update.

```
gauge.setTextField(document.getElementById("preview-textfield"));
```

**Comment by BFTrick** [comment]
I just created a [wiki page](https://github.com/bernii/gauge.js/wiki/How-to-Display-the-Value-of-the-Gauge-in-Text) so that we stop pestering @bernii with questions and he can keep writing awesome code!

**Comment by bernii** [comment]
Big thanks @BFTrick !
