### ISSUE TITLE
Script doe not seem to support Negative Values

### ISSUE THREAD

**Issue by kellyho67** [bernii/gauge.js#20]
To use this for things like temperature it would need to support negative values.  It would be a great update if you could set the start of the gauge somewhere beyond the bottom.  This way you could use temperature and have 0°C in the middle of the gauge and negative to the left and positive temps to the right.

**Comment by kplindegaard** [comment]
This has worked OK for quite some time. Closing the issue.

**Comment by SemihOzden** [comment]
I could not create negative values with bernii's gauge. Could you please provide more info or JS fiddle live demo?
