### ISSUE TITLE
How to render gauge without a pointer

### ISSUE THREAD

**Issue by elias6** [bernii/gauge.js#200]
I am trying to render a gauge without a pointer. How can I do this?

I am looking at the examples on your home page (http://bernii.github.io/gauge.js/), and one of them (the 2nd one) doesn't have a pointer. But I don't see what setting is causing it to not have a pointer. How can I prevent the pointer from rendering?

**Comment by kplindegaard** [comment]
That's the Donut gauge. Check the sample code in the "Usage" section on the page you're referring to. It changes depending on the sample gauge you activate.

**Comment by elias6** [comment]
OK. I didn't notice that the sample code changes when I click the tabs. There is no obvious connection between them, and I couldn't see the sample code change after clicking a tab because it was scrolled off my screen (as it would probably be for most people on your page clicking the tabs). I only discovered the Donut gauge by digging through the code.

Should the Donut be mentioned somewhere in the documentation?
