### ISSUE TITLE
Text in the Center of the Gauge

### ISSUE THREAD

**Issue by peter3099** [bernii/gauge.js#203]
Hi

I just want to accomplished this, 
![image](https://user-images.githubusercontent.com/22412633/53800332-66611b00-3f34-11e9-85bd-4b22b3b69970.png)

I only get this

![image](https://user-images.githubusercontent.com/22412633/53800594-0323b880-3f35-11e9-8c89-0714d5cd5e94.png)

I managed to add the span or the div and the text is showing, but I don't know how to put it inside the canvas or at least on top.

Thanks

**Comment by kplindegaard** [comment]
That's a css/html layout thing. Hope you have figured it out. Closing the issue because it has been 3 months since the question was asked.
