### ISSUE TITLE
Can I use it for my projects?

### ISSUE THREAD

**Issue by WajidAfridi48** [bernii/gauge.js#206]
I am making some projects for myself. I might sell those projects if they are good enough. Do you consent to allow me to use these gauges in my projects? I would be delighted if you agree.
Thank You

**Comment by kplindegaard** [comment]
gauge.js is MIT licensed, so you can basically do whatever you want including using it in a project you change money for provided that reproduce the copyright message and permission notice in your project. Consult the license terms for [MIT license](https://opensource.org/licenses/MIT) and just make sure you follow those.
