### ISSUE TITLE
Gradient does not work.

### ISSUE THREAD

**Issue by nicegoat** [bernii/gauge.js#208]
The gradient does not work. The colorStart does nothing. The entire gauge is the color in the colorStop value. If you put a label at the max value, it gets cut off at the bottom of the gauge canvas.

**Comment by NicFragale** [comment]
I found this too.  Seems the gradient does not take into effect the size of the line itself.  It occurs, just really late.

![image](https://user-images.githubusercontent.com/29712400/55821931-cf9bf700-5abb-11e9-8a54-402a831b49d5.png)

**Comment by vrosu** [comment]
Same here.
