### ISSUE TITLE
Include my vue wrapper for gaugejs

### ISSUE THREAD

**Issue by amroessam** [bernii/gauge.js#209]
Hi @kplindegaard,

I was wondering if you can add a reference to my project in the README.
I've created a vue wrapper for gaugejs for ease of use, cause it was very difficult for me to integrate in my vue project.

Here's the [github link](https://github.com/amroessam/vgauge), and a [demo](https://codesandbox.io/s/jz3qoxny63) with code

**Comment by tifafracica** [comment]
omg! it's just i need it! i gonna try them i'll write you!

**Comment by amroessam** [comment]
Glad I could help :)

**Comment by kplindegaard** [comment]
@amroessam Will do :)
It's perfectly OK for anyone to submit a pull request the README.md for other options that should be listed.
