### ISSUE TITLE
Guage labels as shown here http://bernii.github.io/gauge.js/ does not work out of the box.

### ISSUE THREAD

**Issue by OmkarFatale** [bernii/gauge.js#220]
I added this to options

 staticLabels: {
	  font: "10px sans-serif",  // Specifies font
	  labels: [200, 230, 250, 220.1, 260, 300],  // Print labels at these values
	  color: "#111",  // Optional: Label text color
	  fractionDigits: 0  // Optional: Numerical precision. 0=round off.
	},

tried changing colors but no luck its showing this only.

![download](https://user-images.githubusercontent.com/20432325/67653376-22ad9c80-f96f-11e9-9096-69da29924fa2.png)

**Comment by kplindegaard** [comment]
staticLabels don't work for Donut, only Gauge.

**Comment by shahinlotfi** [comment]
I can't get any labels to show when using the Donut, not even the "main" label shown in the example previews.

**Comment by kplindegaard** [comment]
Use the `setTextField()` method on the Dount object and provide the element you want. 

For example, in your html you have a
```
   <div id="preview-textfield"></div>
```

Pass a ref to that directly after initializing your gauge/donut
```
// Initialize gauge
gauge.setTextField(document.getElementById("preview-textfield"));
```
