### ISSUE TITLE
Can only initialize a total of 3 gauges one page

### ISSUE THREAD

**Issue by JohnWeidmann** [bernii/gauge.js#258]
![guages](https://user-images.githubusercontent.com/14594258/169658919-1b62966f-fc61-4677-96ad-58d7607b5d96.PNG)

has anyone had this issue or know if this is a limitation by design?

**Comment by kplindegaard** [comment]
That sounds weird. Something phony with your html or js logic?
![image](https://user-images.githubusercontent.com/5760583/170877979-d380402e-03b2-4250-833d-fb4c49523439.png)

**Comment by JohnWeidmann** [comment]
oddly enough, I came back to this and it just randomly started working without any code changes. So weird..
