### ISSUE TITLE
gauge.min.js doesn't correlate with gauge.coffee

### ISSUE THREAD

**Issue by andyhmltn** [bernii/gauge.js#27]
Just as a note, I tried using the 'gauge.min.js' that is on the scripts homepage. I've been scratching my head wondering why the colours weren't working. When I compiled the coffeescript version and used that instead, it worked perfect

**Comment by francisdb** [comment]
Was also bitten by this discrepancy

**Comment by andyhmltn** [comment]
I think the best thing to do would be to exclude '.min.js' and provide instructions for building it. Either that, or create a build script and make sure it runs before every push.

**Comment by francisdb** [comment]
That would be nice, my playframework coffee plugin fails to compile the script

**Comment by bernii** [comment]
Sorry and thanks for catching that guys! I'll build a script that will compile it on each push.

**Comment by andyhmltn** [comment]
That's great! This tool has come in really handy these past few days.

**Comment by coreymade** [comment]
Had the same problem....stil not fixed.

**Comment by mpolden** [comment]
Still a problem. gauge.min.js is out of sync with gauge.coffee/gauge.js.

Very difficult to notice why colorStart/colorStop doesn't work, especially when installing through bower.

**Comment by dylanswartz** [comment]
Hey guys, I also experienced this issue with the minified version. I just compiled the coffeescript myself and now the colors work correctly.

**Comment by bernii** [comment]
Recompiled both files
