### ISSUE TITLE
Warning about inappropriate equality comparison with a new object

### ISSUE THREAD

**Issue by szape89** [bernii/gauge.js#273]
With Angular I get the below warning message when running `ng serve`.

```
▲ [WARNING] Comparison using the "!==" operator here is always true [equals-new-object]

    angular:script/global:scripts.js:11:11451:
      11 │ ...p,u,d,g,m,f,x,v,y,V,w,S,M;if(t!=={}){for(l=t.divisions||0,w=t.s...
         ╵                                  ~~~

  Equality with a new object is always false in JavaScript because the equality operator tests object identity. You need to write code to compare the contents of the object instead. For example, use "Array.isArray(x) && x.length === 0" instead of "x === []" to test for an empty array.
```

Based on the warning, the issue is [this line](https://github.com/bernii/gauge.js/blob/gh-pages/dist/gauge.js#L650):  `if (ticksOptions !== {}) {`

**Comment by MrSuddenJoy** [comment]
Use `!=` instead of `!==`

**Comment by kplindegaard** [comment]
This stems from the somewhat naive comparison in the source file `gauge.coffee`, which is where the fix should be done.

**Comment by kplindegaard** [comment]
@szape89 @MrSuddenJoy If you guys wanna take a look and see if this is OK, we can merge and publish this on https://www.npmjs.com/package/gaugeJS

**Comment by szape89** [comment]
@kplindegaard Sorry for the late reply, I was out of office and could not check it. I can confirm that the fix is working. Thank you!
