### ISSUE TITLE
Percentage

### ISSUE THREAD

**Issue by orefalo** [bernii/gauge.js#4]
Very neat project, congrats.

what about a percentage rather than the actual gauge value ?

**Comment by bernii** [comment]
I've added a helper class that wraps text div to help you customize the rendering of the text field.
Here you can find a simple source code (JavaScript) that converts gauge value to percentage :)

``` javascript
gauge = new Gauge(target).setOptions(opts);

var textRenderer = new TextRenderer(document.getElementById('preview-textfield'))
textRenderer.render = function(gauge){
   percentage = gauge.displayedValue / gauge.maxValue
   this.el.innerHTML = (percentage * 100).toFixed(2) + "%"
};
gauge.setTextField(textRenderer);

```

**Comment by singhkumarhemant** [comment]
it worked for me....thanks

**Comment by danielsegg** [comment]
Muito obrigado. Funcionou perfeitamente pra mim.
Eu usei para valor monetário. Deixo o código para ajudar outros Devs.

```
let textRenderer = new TextRenderer(document.getElementById("preview-textfield"))
textRenderer.render = function(gauge) {
    this.el.innerHTML = "R$ " + gauge.displayedValue.toLocaleString("pt-BR");
};
gauge.setTextField(textRenderer);
```
