### ISSUE TITLE
Possibility to use pointer with Donut or extend the arc with Gauge?

### ISSUE THREAD

**Issue by akatsudon** [bernii/gauge.js#40]
I wish to do a Donut gauge with pointer or if the arc of the Gauge type would be able to extend further like Donut and not sitting on a flat line. Just wondering if that's something achievable.

**Comment by kplindegaard** [comment]
If you are still interested, three years is indeed a long time, it is possible indeed :)
You may now tweak the Gauge around all the way if you provide 0 > options.angle >= -0.5. 364a42b7efaad94bc36de9196155e12c69886074
