### ISSUE TITLE
Malformed bower.json

### ISSUE THREAD

**Issue by madtrick** [bernii/gauge.js#50]
The JSON in the `bower.json` file is malformed as there is one extra comma in the `main` property.

``` json
"main": [
    "dist/gauge.js",
    "dist/gauge.min.js",
    "dist/gauge.coffee", <----- This comma
  ],
```

This fails the installation of the component with bower.

**Comment by bernii** [comment]
Thanks! Fixed

**Comment by madtrick** [comment]
Nice. I was going to submit a pr but you were quicker than me : )

**Comment by bernii** [comment]
Yeah it was a quick win so I've just made a change as soon as I got the notification from GitHub :)
