### ISSUE TITLE
Will it be possible to set the radius of the gauge insted of just the line width?

### ISSUE THREAD

**Issue by schlunsen** [bernii/gauge.js#52]

**Comment by hubatish** [comment]
I would also like to do this.

**Comment by jacksoncapper** [comment]
Me too. This would eliminate the Donut class for cleaner, smaller implementation as well.

**Comment by kplindegaard** [comment]
After commit 005b4c93e3ac99eb13852b431f63b4a37abb99ca and the 'radiusScale' option, you can do this now.
