### ISSUE TITLE
gauge size increase (Radius) 

### ISSUE THREAD

**Issue by sohaibali** [bernii/gauge.js#54]
gauge size increase (Radius)

**Comment by hubatish** [comment]
I've found the gauge scales depending on the size of the canvas element it's in.  If you give the canvas element a fixed width & height value (ex: 500x500), the gauge will grow

**Comment by kplindegaard** [comment]
What @hubatish says is correct. In case you want to further scale the gauge radius inside the canvas, you now also have the 'radiusScale' option at your disposal.
