### ISSUE TITLE
Canvas dissapers when values passed through parameters

### ISSUE THREAD

**Issue by AshishRN** [bernii/gauge.js#55]
when values passed through parameters to the function the gauge renders and dissapers

**Comment by farquet** [comment]
Same problem here... When we try to set a specific value, the gauge disappears and there is just a black dot left on screen.

**Comment by alalonde** [comment]
+1

**Comment by AshishRN** [comment]
Hi, Alalonde
is that a solution or you face the same problem

**Comment by farquet** [comment]
I found a solution, at least working for me.
The failing code was gauge.set(speed); with speed being retrieved from some field.
doing simply speed = speed \* 1; solved the problem (automatic conversion from string "10" to int 10). The library seems to be strict on types which is weird for a javascript code... I didn't expect the problem to be here...

**Comment by AshishRN** [comment]
Yes thank you Farquet thank you. Thanks to Alalonde too +1 clicked me too. Gauge.set () Is not taking generated dynamic value, have to manipulate by constant value.
