### ISSUE TITLE
Resize Gauge Element Issues

### ISSUE THREAD

**Issue by jjjrmy** [bernii/gauge.js#68]
Hi,

Having issues resizing the gauge, the element always seems to be wider than the actual guage itself. Is there a way to fix this. Would be much better if it was inline to the guage.

**Comment by okierie** [comment]
Try to make your canvas width be responsive/dynamic! 
`<canvas style="width: 100%;" id="gauge"></canvas>`

**Comment by kplindegaard** [comment]
This has also improved a lot lately. Good tip by @okierie, by the way.

**Comment by lulzia** [comment]
I put canvas inside div with bootstrap class. 
```
<div class="col-md-6 col-lg-2">	
<canvas style="width: 100%;" id="gauge"></canvas>
</div>
```
It was responsive but the resolution is very low.

![immagine](https://user-images.githubusercontent.com/20573952/44729583-6f81b300-aadf-11e8-9c3a-98c957b3ff2c.png)

Have you any ideas?
Thanks

**Comment by Vemb** [comment]
@lulzia Did you ever find a solution to the low resolution problem? I am having the same issue.

**Comment by PowerMeter-company** [comment]
same issue, any suggestion on how to inspect?
![Schermata del 2024-06-01 23-35-50](https://github.com/bernii/gauge.js/assets/118807682/15d8a5d6-941d-4ae3-b77f-580e436ed936)
