### ISSUE TITLE
TypeError: this.canvas is null

### ISSUE THREAD

**Issue by jackmullen2** [bernii/gauge.js#69]
I set it up using the example give at https://bernii.github.io/gauge.js/

Is coffee required also ?  I set it up with out coffee and with coffee .. of course the gauge.js .. 

I get the error "this canvas is null" .. 

Your example works ( in firefox 36 ..) but your example contains far more code than mine .. 

Here is my setup .. just for testing on a server I have in the room .. 

If you have a chance please have a quick look to see 

Errors reported by firebug : 
SyntaxError: illegal character
# Request Animation Frame Polyfill

gauge.coffee (line 1)
TypeError: this.canvas is null
...s.canvas.getContext('2d');this.gp=[new GaugePointer(this)];this.setOptions();thi...
gauge.min.js (line 38)

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Gauge</title>

<script src="/static/script/gauge.min.js" type="application/javascript"></script>

<script src="/static/script/jquery-1.11.2.min.js" type="application/javascript"> </script>

<script src="/static/script/gauge.coffee" type="application/javascript"> </script>

<script>

var opts = {
  lines: 12, // The number of lines to draw
  angle: 0.15, // The length of each line
  lineWidth: 0.44, // The line thickness
  pointer: {
    length: 0.9, // The radius of the inner circle
    strokeWidth: 0.035, // The rotation offset
    color: '#000000' // Fill color
  },
  limitMax: 'false',   // If true, the pointer will not go past the end of the gauge
  colorStart: '#6FADCF',   // Colors
  colorStop: '#8FC0DA',    // just experiment with them
  strokeColor: '#E0E0E0',   // to see which ones work best for you
  generateGradient: true
};

var target = document.getElementById('foo'); // your canvas element
var gauge = new Gauge(target).setOptions(opts); // create sexy gauge!
gauge.maxValue = 3500; // set max gauge value
gauge.animationSpeed = 32; // set animation speed (32 is default value)
gauge.set(3000); // set actual value
</script>
 

/**/
</script>
</head>

<body>

<canvas id="foo"></canvas>
</body>
</html>

**Comment by yenda** [comment]
You have to make a div and target its id in the line commented // your canvas element

**Comment by kplindegaard** [comment]
Solution given. Closing the issue.
