### ISSUE TITLE
Added gauge value in text, gauge disappears

### ISSUE THREAD

**Issue by brianmickelson** [bernii/gauge.js#70]
returning the following errors:

Uncaught TypeError: undefined is not a function
formatNumber                    gauge.js:85
TextRenderer.render         gauge.js:255
Gauge.render                    gauge.js:571
ValueUpdater.update         gauge.js:165
window.AnimationUpdater.run     gauge.js:753

**Comment by vcanales** [comment]
Some of your code would be a good idea.

**Comment by brianmickelson** [comment]
I used a workaround. I'll see if i can replicate again.

**Comment by kplindegaard** [comment]
Just be sure to provide a numerical value in the .set( ) function. Closing the issue.
