### ISSUE TITLE
Multiple gauge Problem

### ISSUE THREAD

**Issue by Sharagim** [bernii/gauge.js#72]
Hi,
When using multiple instance of the gauge, all pointers have been overwritten by last pointer setting.
https://jsfiddle.net/d1ygogps/5/

**Comment by sohandsouza** [comment]
I believe I am encountering the same problem. If I change the color of one gauge's pointer, the color of the other one's pointer changes too, even though they are set with different option objects.

**Comment by jonkpirateboy** [comment]
I have the same problem.

**Comment by HunterJoe** [comment]
Updated your fiddle to use the correct instance of the gage in the first gauge's set method. 
https://jsfiddle.net/HunterJoe/25tn1zw3/

Also your max value on the first gauge was 0.

**Comment by Sharagim** [comment]
Thx for reply.
I put "gauge1.set(1260);" again and you can see what is happening.
Please see:
https://jsfiddle.net/30ujm879/

**Comment by HunterJoe** [comment]
ok, so your latest fiddle does indeed work, and it is doing exactly what you are telling it to do.

You have gauge1.set(10) at the very bottom of your fiddle (line 44). Remove that, and it will "gauge" to the value set earlier of 1100, on line 20.

**Comment by Sharagim** [comment]
So how we can change values on fly? I have a ajax job which read values and I want to update them.

**Comment by HunterJoe** [comment]
I do not believe there is a way to update the value in the fly. I do not think this script works that way, nor was meant to work that way.

I am sure it can be achieved, but it would not be a simple process. I'll try to work out a fiddle for you.

**Comment by Sharagim** [comment]
Thx for your reply.
Currently I am doing it in this way:
I put the OBJECT to a jquery data and each 5 sec a script will update each gauge according to last value. The only problem is this problem which you can see.

**Comment by sohandsouza** [comment]
Hi, HunterJoe.

The pointer color setting for a single gauge is still overwriting pointers across all gauges. Am I setting it wrong?
https://jsfiddle.net/qjmdwcfy/

**Comment by HunterJoe** [comment]
No it looks like you are doing it right, this actually looks to be a bug in the core plugin.

Having multiple instances of the gauge does not allow for individual pointer colors, it instead picks up the settings from the last gauge instance. I would report this as a bug.

gauge1 pointer should be red.
gauge2 pointer should be blue.
Both are blue.
https://jsfiddle.net/HunterJoe/25tn1zw3/2/

**Comment by sohandsouza** [comment]
Wow, then it happens even if the pointer color is set in the initial declaration of the options.
