### ISSUE TITLE
Make it compatible with AMD

### ISSUE THREAD

**Issue by ThomasCrevoisier** [bernii/gauge.js#76]
I'm currently working on an application that uses RequireJS to load modules. The problem is that I can't require your module this way. Could you consider adding this feature in future releases ?

**Comment by bernii** [comment]
Do you have time to create a PR with the changes (to allow both stand-alone import and amd)?

**Comment by ThomasCrevoisier** [comment]
Yep, I can take a look at it and submit a PR during the week. (Also, I thought it would be convenient to add instructions for those who wants to contribute to the project :) I am not a CoffeeScript expert, so I don't really know how to produce `gauge.js` and `gauge.min.js` files).

**Comment by ThomasCrevoisier** [comment]
Fixed in #77
