### ISSUE TITLE
pointer and gauge fill don't line up

### ISSUE THREAD

**Issue by leviwolfe** [bernii/gauge.js#8]
Repro case here: http://jsfiddle.net/yXc5J/

The pointer is not lining up exactly in between the blue fill color and the grey stroke color.

**Comment by bernii** [comment]
Fixed! Thanks for pointing that out. The bug was introduced during recent changes in rendering chain and animation speed control.

**Comment by leviwolfe** [comment]
Thanks for the quick fix and the great script!
