### ISSUE TITLE
Background color in donut.

### ISSUE THREAD

**Issue by aliakakis** [bernii/gauge.js#9]
Hello and congratulations on the excellent work. I do not seem to be able to have the background color(strokeColor) to work on the donut even when using your example with the sliders. Is this a browser issue or am I doing something wrong? (Google Chrome 22).

**Comment by bernii** [comment]
Sorry for such a late response, totally missed it! It should work, I've just tested it on my OSX with Chrome 22, Firefox 15 & 16 and Opera 12. 

Working example: http://jsfiddle.net/Sh7a8/
Screenshot: http://cl.ly/image/0v3m1J2Z0y0D

How does it behave on your setup? And what is the setup ;) ?

**Comment by aliakakis** [comment]
Thank you for the reply. Unfortunately I haven't been able to reproduce it. http://jsfiddle.net/Sh7a8/1/ I changed strokeColor to black but I was able to have a black background.

**Comment by bernii** [comment]
Ok, now I see your point. Fixed!

Fiddle: http://jsfiddle.net/Sh7a8/5/
