### ISSUE TITLE
Skip animation

### ISSUE THREAD

**Issue by mrbase** [bernii/gauge.js#92]
Is there any way to skip the animations and just show the finished gauge and value ?

**Comment by lorenzo-baldacci** [comment]
try increasing the animationSpeed property up to 10000.

**Comment by mrbase** [comment]
will try - closing this

**Comment by ardahankul** [comment]
It is not worked for me

**Comment by slabbdev** [comment]
Gauge.animationSpeed = 1; will do the tricks ;)
